version: '2.3'
services:
  notebook:
    build: .
    ports:
      - "8888:8888"

  docs:
    build: .
    ports:
      - "3000:3000"
    entrypoint: /bin/bash -c "cd /src/nnfabrik/docs/; make html; cd _build/html; python -m http.server 3000"